name: Version Increment

on:
  push:
    branches: [main]

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: git config
        run: git config --global user.name 'Wurmloch' && git config --global user.email 'dominik@mueteam.de'
      - name: Patch Version main ⬆️
        run: npm version patch -m "[RELEASE] %s"
      - name: Patch Version in Component ⬆️
        run: npm version patch -m "[RELEASE] %s"
        working-directory: projects/ngx-stereo-card
      - name: Push new Version ✔️
        run: git push
